name: Run FPL Bot

on:
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 UTC
  workflow_dispatch:        # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   # also update checkout to v4 (latest)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python bot.py

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4   # ✅ new version
        with:
          name: bot-output
          path: output/
