name: Daily FPL Bot

on:
  schedule:
    - cron: '10 4 * * *'  # 10:10 AM BST = 4:10 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run FPL bot
      run: python src/fpl_bot.py

    - name: Configure Git
      run: |
        git config --global user.name 'FPL Bot'
        git config --global user.email 'bot@example.com'

    - name: Commit bot output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add output/ docs/
        git commit -m "FPL Bot update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
