name: Daily FPL Bot

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write  # ✅ Required for pushing commits

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # ✅ Don't use default creds

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run bot
      run: python src/fpl_bot.py

    - name: Commit output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'FPL Bot'
        git config --global user.email 'bot@example.com'
        git add output/
        git commit -m "Daily FPL update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
